---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-ci-cd-web-app-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: test-ci-cd-web-app-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-ci-cd-web-app-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: test-ci-cd-web-app-sa
  namespace: default
roleRef:
  kind: Role
  name: test-ci-cd-web-app-role
  apiGroup: rbac.authorization.k8s.io
