apiVersion: v1
kind: Service
metadata:
  name: test-ci-cd-web-app
  namespace: default
spec:
  selector:
    app: test-ci-cd-web-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
  type: LoadBalancer
